###
POST http://localhost:3000/users
Content-Type: application/json

{
    "first_name": "Karthik",
    "last_name": "Donthaboyina",
    "email": "karthik@gmail.com"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/actors

###
GET http://localhost:3000/countries

###
GET http://localhost:3000/actors/8

###
GET http://localhost:3000/films

###
GET http://localhost:3000/film-actors


###
GET http://localhost:3000/actor-movies


# --------------------------------------
###
GET http://localhost:3000/api/advanced/joins/cities